version: "3.9"

services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: barbergo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  loki:
    image: grafana/loki:3.4.1
    container_name: barbergo-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ../observability/loki/loki-config.yml:/etc/loki/local-config.yaml:ro

  grafana:
    image: grafana/grafana:11.5.2
    container_name: barbergo-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
      - loki
